name: Check Lint

on: pull_request

jobs: 
  check_lint:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        elixir: [1.14]
        otp: [25]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
